services:
  - type: web
    name: laravel-backend
    env: docker
    plan: free
    repo: https://github.com/fernanjps/esto-es-una-prueba
    region: oregon
    branch: main
    rootDir: backend

  - type: web
    name: react-frontend
    env: docker
    plan: free
    repo: https://github.com/fernanjps/esto-es-una-prueba
    region: oregon
    branch: main
    rootDir: frontend
